@extends('layouts.app')

@section('content')
<style>
.pir-header{display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,420px);gap:2rem;align-items:end;padding:1.35rem;border:1px solid #d9dee5;border-radius:6px;background:#fff}.pir-header h1{margin:.15rem 0 .35rem;font-size:1.55rem}.pir-header p{margin:0;color:#667085}.pir-eyebrow{color:#0d6efd;font-size:.75rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.pir-filter label{display:block;margin-bottom:.4rem;font-size:.8rem;font-weight:700}.pir-loader{display:flex;justify-content:center;align-items:center;gap:.65rem;min-height:56px;color:#667085}.pir-list{display:grid;gap:1rem}.pir-product{display:grid;grid-template-columns:minmax(230px,320px) minmax(0,1fr);gap:1.1rem;padding:1rem;border:1px solid #d9dee5;border-radius:6px;background:#fff;content-visibility:auto;contain-intrinsic-size:230px}.pir-product-meta{border-right:1px solid #d9dee5;padding-right:1rem}.pir-reference{display:inline-flex;align-items:center;gap:.45rem;font-size:1rem;font-weight:800;word-break:break-word}.pir-name{margin-top:.55rem;line-height:1.4}.pir-id{margin-top:.55rem;font-size:.75rem;color:#667085}.pir-gallery{display:flex;gap:.75rem;overflow-x:auto;padding:.1rem .1rem .55rem;scroll-snap-type:x proximity}.pir-image-link{position:relative;flex:0 0 150px;height:150px;display:grid;place-items:center;overflow:hidden;border:1px solid #d9dee5;border-radius:6px;background:#fff;scroll-snap-align:start}.pir-image-link img{width:100%;height:100%;object-fit:contain}.pir-cover,.pir-image-number{position:absolute;padding:.15rem .4rem;border-radius:4px;color:#fff;font-size:.68rem}.pir-cover{top:.35rem;left:.35rem;background:#0d6efd;font-weight:800;text-transform:uppercase}.pir-image-number{right:.35rem;bottom:.35rem;background:rgba(15,23,42,.75)}.pir-no-images{min-height:150px;display:grid;place-items:center;width:100%;border:1px dashed #c5ccd5;border-radius:6px;color:#667085}.pir-sentinel{height:2px}@media(max-width:900px){.pir-header,.pir-product{grid-template-columns:1fr}.pir-product-meta{border-right:0;border-bottom:1px solid #d9dee5;padding:0 0 1rem}}
</style>

<div id="productImageReview" data-products-url="{{ route('marketing.product_images.products') }}">
    <div class="pir-header mb-3">
        <div><div class="pir-eyebrow">Marketing · ASM</div><h1>Product Image Review</h1><p>Seleciona uma marca para rever todas as referências e fotografias associadas.</p></div>
        <div class="pir-filter"><label for="pirManufacturer">Marca ASM</label><select id="pirManufacturer" class="form-control"><option value="">Selecionar uma marca…</option>@foreach($manufacturers as $manufacturer)<option value="{{ $manufacturer->id_manufacturer }}">{{ $manufacturer->name }} ({{ number_format($manufacturer->product_count,0,',','.') }})</option>@endforeach</select></div>
    </div>
    <div class="pir-list" id="pirList"></div>
    <div class="pir-loader" id="pirLoader" hidden><i class="fa-solid fa-spinner fa-spin"></i><span>A carregar mais 10 produtos…</span></div>
    <div class="pir-sentinel" id="pirSentinel"></div>
</div>

<script>
document.addEventListener('DOMContentLoaded',()=>{const root=document.getElementById('productImageReview'),select=document.getElementById('pirManufacturer'),list=document.getElementById('pirList'),loader=document.getElementById('pirLoader'),sentinel=document.getElementById('pirSentinel');let manufacturer='',page=0,loading=false,more=false,version=0;const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};function render(p){const card=el('article','pir-product'),meta=el('div','pir-product-meta'),ref=el('div','pir-reference'),gallery=el('div','pir-gallery');ref.append(el('i','fa-solid fa-barcode'),document.createTextNode(p.reference));meta.append(ref,el('div','pir-name',p.name),el('div','pir-id',`Produto #${p.id_product}`));if(!p.images.length)gallery.append(el('div','pir-no-images','Sem imagens'));p.images.forEach((image,i)=>{const a=el('a','pir-image-link'),img=document.createElement('img');a.href=image.large_url;a.target='_blank';a.rel='noopener';a.title=`${p.reference} · imagem ${i+1}`;img.src=image.thumbnail_url;img.alt=`${p.reference} · ${p.name} · imagem ${i+1}`;img.loading='lazy';img.decoding='async';img.addEventListener('error',()=>{img.remove();a.prepend(el('i','fa-solid fa-triangle-exclamation text-warning fa-2x'))},{once:true});a.append(img);if(image.cover)a.append(el('span','pir-cover','Capa'));a.append(el('span','pir-image-number',String(i+1)));gallery.append(a)});card.append(meta,gallery);list.append(card)}async function load(){if(!manufacturer||loading||!more)return;loading=true;loader.hidden=false;const current=version;try{const url=new URL(root.dataset.productsUrl,location.origin);url.searchParams.set('manufacturer_id',manufacturer);url.searchParams.set('page',String(page+1));const response=await fetch(url,{headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest'}});if(!response.ok)throw new Error(response.status);const payload=await response.json();if(current!==version)return;payload.data.forEach(render);page=payload.meta.page;more=payload.meta.has_more}catch(e){if(current===version)list.append(el('div','alert alert-danger','Não foi possível carregar os produtos. Tenta novamente.'))}finally{if(current===version){loading=false;loader.hidden=true}}}select.addEventListener('change',()=>{version++;manufacturer=select.value;page=0;more=Boolean(manufacturer);loading=false;list.replaceChildren();loader.hidden=true;if(!manufacturer)return;load()});new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))load()},{rootMargin:'600px 0px'}).observe(sentinel)});
</script>
@endsection
